kind: PersistentVolume
apiVersion: v1
metadata:
  name: flask-vol-pv
  namespace: mysql
  labels:
    type: local
    app: flask
spec:
  storageClassName: local-storage
  capacity:
     storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: flask-vol-pvc
  namespace: mysql
  labels:
    type: local
    app: flask
spec:
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany

