kind: PersistentVolume
apiVersion: v1
metadata:
  name: mysql-pv-vol
  namespace: mysql
  labels:
    type: local
    app: mysql
spec:
  storageClassName: local-storage
  capacity:
     storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: mysql-pvc-vol
  namespace: mysql
  labels:
    type: local
    app: mysql
spec:
  storageClassName: local-storage
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteMany
