apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mysqls.com.poc.persistent
spec:
  group: com.poc.persistent
  names:
    kind: MySql
    listKind: MySqlList
    plural: mysqls
    singular: mysql
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1
    served: true
    storage: true
