apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: flasks.com.poc.persistent 
spec:
  group: com.poc.persistent
  names:
    kind: Flask
    listKind: FlaskList
    plural: flasks
    singular: flask
  scope: Namespaced
  subresources:
    status: {}
  versions:
  - name: v1
    served: true
    storage: true
