---

- name: Converge
  hosts: localhost
  connection: local
  vars:
    ansible_python_interpreter: '{{ ansible_playbook_python }}'
    deploy_dir: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/deploy"
    image_name: com.poc.persistent/mysql:testing
    custom_resource: "{{ lookup('file', '/'.join([deploy_dir, 'crds/com.poc.persistent_v1_mysql_cr.yaml'])) | from_yaml }}"
  tasks:
  - name: Create the com.poc.persistent/v1.MySql
    k8s:
      namespace: '{{ namespace }}'
      definition: "{{ lookup('file', '/'.join([deploy_dir, 'crds/com.poc.persistent_v1_mysql_cr.yaml'])) }}"

  - name: Get the newly created Custom Resource
    debug:
      msg: "{{ lookup('k8s', group='com.poc.persistent', api_version='v1', kind='MySql', namespace=namespace, resource_name=custom_resource.metadata.name) }}"

  - name: Wait 2m for reconciliation to run
    k8s_facts:
      api_version: 'v1'
      kind: 'MySql'
      namespace: '{{ namespace }}'
      name: '{{ custom_resource.metadata.name }}'
    register: reconcile_cr
    until:
    - "'Successful' in (reconcile_cr | json_query('resources[].status.conditions[].reason'))"
    delay: 12
    retries: 10

- import_playbook: '{{ playbook_dir }}/../default/asserts.yml'
